# Generated by Django 4.0.3 on 2022-03-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.ManyToManyField(to='registration.profile')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_check', models.CharField(default='service', editable=False, max_length=8)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('description', models.TextField(max_length=10000, verbose_name='description')),
                ('description_ru', models.TextField(max_length=10000, null=True, verbose_name='description')),
                ('description_en', models.TextField(max_length=10000, null=True, verbose_name='description')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('created_at', models.DateField(default=None, editable=False, null=True, verbose_name='created date')),
                ('status', models.CharField(choices=[('m', 'У модерации'), ('a', 'Активное'), ('i', 'Неактивное')], default='d', max_length=1, verbose_name='status')),
                ('image', models.ImageField(null=True, upload_to='services/%Y_%m_%d', verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='product')),
            ],
            options={
                'db_table': 'services',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_check', models.CharField(default='good', editable=False, max_length=8)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('description', models.TextField(max_length=10000, verbose_name='description')),
                ('description_ru', models.TextField(max_length=10000, null=True, verbose_name='description')),
                ('description_en', models.TextField(max_length=10000, null=True, verbose_name='description')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('created_at', models.DateField(default=None, editable=False, null=True, verbose_name='created date')),
                ('status', models.CharField(choices=[('m', 'У модерации'), ('a', 'Активное'), ('i', 'Неактивное')], default='d', max_length=1, verbose_name='status')),
                ('image', models.ImageField(null=True, upload_to='goods/%Y_%m_%d', verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='product')),
            ],
            options={
                'db_table': 'goods',
                'ordering': ['created_at'],
            },
        ),
    ]
