# Generated by Django 2.2 on 2022-03-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('m', 'У модерации'), ('a', 'Активное'), ('i', 'Неактивное')], default='d', max_length=1, verbose_name='status'),
        ),
    ]
