# Generated by Django 2.2 on 2022-03-07 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220307_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='created_at',
            field=models.DateField(verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='servicesimage',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_images', to='shop.Service'),
        ),
    ]
