# Generated by Django 2.2 on 2022-03-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220307_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesimage',
            old_name='goods',
            new_name='service',
        ),
    ]
