# Generated by Django 2.2 on 2022-03-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20220307_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimages',
            name='image',
            field=models.ImageField(upload_to='goods/%Y_%m_%d', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='servicesimage',
            name='image',
            field=models.ImageField(upload_to='services/%Y_%m_%d', verbose_name='image'),
        ),
    ]
