# Generated by Django 2.2 on 2022-03-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220310_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='status',
            field=models.CharField(choices=[('m', 'У модерации'), ('a', 'Активное'), ('i', 'Неактивное')], default='d', max_length=1, verbose_name='status'),
        ),
    ]
